[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/saihtaungkham/Secure-and-Private-AI-Myanmar-Resources/blob/master/Section(4)/Local_Differential_Privacy_MM.ipynb)

ဒီ Notebook မှာတော့ ကျွန်တော်တို့ Local Differential Privacy မှာ ထည့်ပေါင်းထားတဲ့ Noise ကိုဘယ်လိုဖယ်ရှားနိုင်လဲ ဆိုတဲ့ လက်တွေ့ကို ပြုလုပ်မှာဖြစ်ပါတယ်။ <br>
(၁) အရင်ဆုံးကျွန်တော်တို့ လိုအပ်တဲ့ Dataset ကိုတည်ဆောက်ရမှာဖြစ်ပါတယ်။ <br>
(၂) အဲ့ဒီ Dataset ကတော့ ကျွန်တော်တို့ Survey ကောက်လို့ရလာတဲ့ ရလဒ်လို့ပဲ ယူဆရအောင်လားဗျာ။

In [1]:
# အရင်ဆုံးကျွန်တော်တို့ Simulation လုပ်ဖို့အတွက် လိုအပ်တဲ့ Library ကို Import လုပ်မှာ ဖြစ်ပါတယ်။

import numpy as np

In [2]:
# ဒါကတော့ ကျွန်တော်တို့ Random Number ကို Generate လုပ်မှာဖြစ်ပါတယ်။
# လူအယောက်တစ်ရာဆီက Survey ကိုကောက်တယ်လို့ သဘောထားပါ။
# ၀ နဲ့ ၁ ကတော့ မေးခွန်းမေးပြီး လုပ်ဖူးတယ်ဆိုရင် ၁ ကို ဖြေကြမှာ၊ မလုပ်ဖူးရင်တော့ ၀ ကို ဖြေတယ်လို့ယူဆပါ။

(np.random.rand(100) > 0.5).astype('uint8')

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1], dtype=uint8)

In [3]:
survey_db = (np.random.rand(100) > 0.5).astype('uint8')

In [4]:
# ဒီနေရာမှာတော့ စုစုပေါင်းရလဒ်အစား ကျွန်တော် ပျမ်းမျှရှာထားတာဖြစ်ပါတယ်။
# ဒီတန်ဖိုးကို မှတ်ထားပါ။ အမှန်တကယ် Real World မှာဖြစ်ပျက်နေတဲ့ ရလဒ်ဖြစ်ပါတယ်။

survey_db.astype('float').mean()

0.54

In [5]:
# ပထမအကြိမ် အကြွေစေ့ကို လှိမ့်လို့ရလာတဲ့ ရလဒ်ဖြစ်ပါတယ်။
# လူအယောက် ၁၀၀ ရှိတဲ့အတွက် အကြိမ် ၁၀၀ အကြွေစေ့လှိမ့်တာနဲ့ တူတူပါပဲ။
# 1 သည် ခေါင်းကို ရည်ညွှန်းပြီး 0 သည် ပန်းကို ရည်ညွှန်းတာဖြစ်ပါတယ်။

first_coin_flip = (np.random.rand(100) > 0.5).astype('uint8')

In [6]:
first_coin_flip

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=uint8)

In [7]:
# ဒါကတော့ ဒုတိယ အကြိမ်အကြွေစေ့ လှိမ့်တဲ့ Simulation ပါ။

second_coin_flip = (np.random.rand(100) > 0.5).astype('uint8')

In [8]:
second_coin_flip

array([0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0], dtype=uint8)

In [9]:
# အမှန်တကယ် အဖြေနဲ့ ပထမ အကြွေစေ့ရဲ့ ရလဒ်ကို မြှောက်တာပါ။
# ရည်ရွယ်ချက်ကတော့ ပထမအကြိမ်အကြွေစေ့လှိမ့်တဲ့နေရာမှာ ခေါင်း (1) ကျခဲ့ရင် ရိုးသားစွာဖြေဆိုရမှာပါ။
# ဒါကြောင့် လုပ်ဖူးတယ် (1) * ခေါင်း (1) ဆိုရင် အဲ့လူရဲ့ Survey ရဲ့ရလဒ်ဟာ 1 ဖြစ်နေမှာပါ။

survey_db * first_coin_flip

array([1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=uint8)

In [10]:
# ဒါကတော့ ဒုတိယအကြွေစေ့အတွက်ဖြစ်ပါတယ်။ တကယ်လို့ ပထမအကြွေစေ့မှာ ပန်း (0) ကျခဲ့မယ်ဆိုရင် 
# ဒုတိယ အကြွေစေ့ကို လှိမ့်ဖို့လိုအပ်လာပါပြီ။ ဒုတိယအကြွေစေ့မှာ ခေါင်း (1) ကျခဲ့ရင် လုပ်ဖူးတယ် (1)
# လို့ဖြေရပါမယ်။ ပန်း (0) ကျရင်တော့ မလုပ်ဖူးဘူး (0) လို့ဖြေရမှာပါ။

# (1 - first_coin_flip) -> ပထမမှာ ပန်းကျခဲ့မယ်ဆိုရင်
# (1- first_coin_flip) * second_coin_flip -> ဒုတိယ အကြွေစေ့ရဲ့ရလဒ်ကို ယူမယ်။
# (1 - 0) * (1 or 0) = (1 * (1 or 0)) -> Second coin result!

(1 - first_coin_flip) * second_coin_flip

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [11]:
# (survey_db.astype('float') * first_coin_flip) -> ပထမ အကြွေစေ့မှာ ခေါင်းဆိုရင် Survey_db (အမှန်) အတိုင်းဖြေ
# (1 - first_coin_flip) * second_coin_flip -> ပထမမှာ ပန်းကျခဲ့မယ်ဆိုရင် ဒုတိယ အကြွေစေ့ရဲ့ရလဒ်ကို ယူမယ်။

survey_db_with_noise = (survey_db.astype('float') * first_coin_flip) + (1 - first_coin_flip) * second_coin_flip

In [12]:
# နောက်ဆုံးမှာ ကျွန်တော်တို့ Noise ပါတဲ့ Survey ရလဒ်ရလာပါပြီ။

survey_db_with_noise

array([1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0.])

In [13]:
# အပေါ်မှာ Noise မပါတဲ့ ရလဒ်ဟာ 0.54 ပါ။ Noise ပေါင်းလိုက်တော့ 0.53 ဖြစ်သွားပါတယ်။
survey_db_with_noise.astype('float').mean()

0.53

In [14]:
# Noise ကိုဖယ်ရှားဖို့ Equation ပါ။ အပိုင်း (၃) မှာဖော်ပြထားပါတယ်။
# သို့သော်ငြားလည်း အဖြေမှန်သည် 0.54 ပါ။ ကျွန်တော်တို့ရလာတဲ့ ရလဒ်သည် 0.56 ပါမှားနေပါတယ်။
# ဒါပေမယ့် Law of Large Numbers အရ ကျွန်တော်တို့သည် Survey ကောက်တဲ့ လူဦးရေများလေလေ
# တစ်နည်းအားဖြင့် အကြွေစေ့ကို များများလှိမ့်လေလေ ကျွန်တော်တို့ Noise ဖယ်ရှားတဲ့နေရာမှာ မှန်ကန်တဲ့ 
# ရလဒ် ရလေပဲဖြစ်ပါတယ်။

survey_db_with_noise.astype('float').mean() * 2 - 0.5

0.56

In [15]:
# ဒါကတော့ အပေါ်မှာ ဖော်ပြခဲ့တဲ့ အဆင့်တွေအားလုံးကို Function နဲ့ပြန်ရေးထားတာပဲဖြစ်ပါတယ်။
def do_survey(survey_data):
    # Real World ကတကယ့်ဖြစ်ပျက်နေတဲ့ အချက်အလက်ရဲ့ ပျမ်းမျှ
    actual_result = survey_data.astype('float').mean()
    
    # Coin လှိမ့်တဲ့ Simulation ပါ
    first_coin_flip = (np.random.rand(len(survey_data)) > 0.5).astype('uint8')
    second_coin_flip = (np.random.rand(len(survey_data)) > 0.5).astype('uint8')
    
    survey_db_with_noise = (survey_data.astype('float') * first_coin_flip) + (1 - first_coin_flip) * second_coin_flip
    
    # Noise ကိုဖယ်ရှားတာပါ
    remove_noise = survey_db_with_noise.astype('float').mean() * 2 - 0.5
    
    # Real World ရလဒ်နဲ့ Noise ဖယ်ရှားပြီးသား ရလဒ်ပါ
    return actual_result, remove_noise

In [16]:
do_survey(survey_db)

(0.54, 0.48)

In [20]:
# Survey မှာ လူ ၁၀ ယောက်၊ အယောက် ၁၀၀၊ ၁၀၀၀၊ ၁၀၀၀၀ နဲ့ Simulation လုပ်ကြည့်ပါမယ်။
# သတိထားရမယ့်အချက်ကတော့ Survey လုပ်တဲ့ လူအရေအတွက်များလာလေ Real World ရဲ့ရလဒ်နဲ့
# Noise ဖယ်ရှားပြီးသား ရလဒ် တဖြည်းဖြည်း နီးကပ်လာတာကို တွေ့ရမှာပါ။
# ဒါကတော့ Law of Large Numbers မှန်ကန်ကြောင်း သက်သေပြတာနဲ့ ကျွန်တော့်တို့ Equation မှန်ကန်
# ကြောင်း သက်သေပြတာပါ။

for item in [10, 100, 1000, 10000]:
    # Real World ကတကယ့်ဖြစ်ပျက်နေတဲ့ အချက်အလက်ကို ဖန်တီးခြင်း
    db = (np.random.rand(item) > 0.5).astype('uint8')
    private_result, true_result = do_survey(db)
    print("With Noise:" + str(private_result))
    print("Noise Removed:" + str(true_result))
    print("......")

With Noise:0.5
Noise Removed:0.09999999999999998
......
With Noise:0.51
Noise Removed:0.48
......
With Noise:0.495
Noise Removed:0.46199999999999997
......
With Noise:0.4941
Noise Removed:0.4952
......
